#!/bin/bash

docker pull melissan/docker_hearts_security
echo './compare.py /home/test; echo $? > /home/extract.txt' | docker run -i -v "$(pwd)":/home melissan/docker_hearts_security /bin/bash
docker cp $(docker container ls -a | head -n 2 | tail -n 1 | rev | cut -d " " -f1 | rev):/home/extract.txt /home/dockerhearts

#cd /home
#git clone https://github.com/MelissaN/DockerHeartsSecurity.git
#cd DockerHeartsSecurity
#echo "#!/bin/bash" > test
#echo "ls > Heart.txt" >> test
#chmod u+x test
#./check_heart_status
